Run unit tests across Python versions 3.10-3.12. (#326)
Also updated enough of the project to pass these new test
configurations:

* Avoid starred expressions in indexes for Python < 3.11
(https://stackoverflow.com/a/77080166,
https://stackoverflow.com/q/77580216)
* Import `Self` from `typing_extensions` for Python < 3.11
(https://stackoverflow.com/a/77247460)
* Limit use of `logger.getLevelNamesMapping` to Python >= 3.11
(https://docs.python.org/3/library/logging.html#logging.getLevelNamesMapping,
see also
https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks)
* Stop using `unittest` in files that don't need it, fixing exit code 5
in Python >= 3.12 for "no tests were run"
(https://docs.python.org/3/library/unittest.html#unittest.main)

---------

Co-authored-by: Marius Brehler <marius.brehler@gmail.com>

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -22,11 +22,12 @@ concurrency:
 
 jobs:
   test:
-    name: "Unit Tests and Type Checking"
+    name: "${{ matrix.os }} :: ${{ matrix.version }} :: Unit Tests and Type Checking"
     strategy:
       fail-fast: false
       matrix:
-        version: [3.11]
+        # Support for Python 3.13 depends on https://github.com/pytorch/pytorch/issues/130249
+        version: ["3.10", "3.11", "3.12"]
         os: [ubuntu-22.04]
     runs-on: ${{matrix.os}}
     env:
@@ -71,3 +72,23 @@ jobs:
         if: ${{ !cancelled() }}
         run: |
           mypy
+
+  # Depends on all other jobs to provide an aggregate job status.
+  ci_summary:
+    if: always()
+    runs-on: ubuntu-20.04
+    needs:
+      - test
+    steps:
+      - name: Getting failed jobs
+        run: |
+          echo '${{ toJson(needs) }}'
+          FAILED_JOBS="$(echo '${{ toJson(needs) }}' \
+            | jq --raw-output \
+            'map_values(select(.result!="success" and .result!="skipped")) | keys | join(",")' \
+          )"
+          echo "failed-jobs=${FAILED_JOBS}" >> $GITHUB_OUTPUT
+          if [[ "${FAILED_JOBS}" != "" ]]; then
+            echo "The following jobs failed: ${FAILED_JOBS}"
+            exit 1
+          fi
